name: WorldChatter
version: 1.2.9
main: mc.omaromar93.classes.WorldChatter
authors: [ OmarOmar93 ]
description: Every world deserves its own conversation.
softdepend:
  - PlaceHolderAPI
commands:
  worldchatter:
    description: The main command of WorldChatter
    aliases:
      - wc